### ISSUE TITLE
Implement Tailwind CSS

### ISSUE THREAD

**Issue by Lottike** [Dax89/electron-sveltekit#3]
Hey, I'm quite new to electron. Any advice on how to implement TailwindCSS in this project?

**Comment by Dax89** [comment]
Hi!
Just follow Svelte(Kit) and TailwindCSS documentation.

If (for some case) you need to use the electron part, there is an `ipc` global variable defined here: https://github.com/Dax89/electron-sveltekit/blob/master/src/app.html#L8
Electron's documentation provides all informations you need.

**Comment by Lottike** [comment]
Perfect! Thank you!
