### ISSUE TITLE
Update to latest SvelteKit

### ISSUE THREAD

**Issue by DogFoxX** [Dax89/electron-sveltekit#9]
Anyway we can get updated code to use the latest SvelteKit?

**Comment by Dax89** [comment]
Yep, I will check this week

**Comment by Dax89** [comment]
I have tried to migrate to the new folder based routing system, there are some issue when I use the adapter-static: basically it doesn't navigate to page1, page2 and page3.

There are no errors, it just display the homepage again and again. It works fine with the adapter-node

I will investigate more

**Comment by DogFoxX** [comment]
It's working for me. I started a brand new skeleton sveltekit project and used some of your code to implement it into electron using `adapter-static`. When I'm done I will upload my repo and you can have a look.
The first issue I fount was to change the `electron` script in `package.json` to `electron .` instead of `electron src/electron.cjs`.
My scripts:
```json
"scripts": {
  "dev": "cross-env NODE_ENV=dev npm run dev:all",
  "dev:all": "concurrently -n=svelte,electron -c='#ff3e00',blue \"npm run dev:svelte\" \"npm run dev:electron\"",
  "dev:svelte": "vite dev --host --port 3000",
  "dev:electron": "electron .",
  "build": "cross-env NODE_ENV=production npm run build:svelte && npm run build:electron",
  "build:svelte": "vite build",
  "build:electron": "electron-builder build --win --publish never",
  "postinstall": "svelte-kit sync"
},
```
Just start with `npm run dev`.
I don't recall if this was the only thing, but folder based routing is working for me in development and after building.

**Comment by Dax89** [comment]
Yep it works with `npm run dev`.
The issue is when the application is packaged with `npm run package` and I try the bundled electron one

**Comment by DogFoxX** [comment]
Try my scripts and see if it'll work. Like I said, mine works in development and packaged.

**Comment by DogFoxX** [comment]
I uploaded my project here:
https://github.com/DogFoxX/electron-sveltekit-tailwind

Still need to refine the Reame lol
